cors:
  allowed-origins: https://user-manager-frontend-eight.vercel.app
  allowed-methods: GET
  allowed-headers: "*"
  allow-credentials: true
jsonplaceholder:
  baseUrl: https://jsonplaceholder.typicode.com/
  expiresAfter: 24 #hours
spring:
  application:
    name: user_manager_backend
